image: Visual Studio 2015
version: '{branch}.{build}'

cache:
  - c:\build-cache -> .appveyor.yml, .appveyor/*.cmd

environment:
  GITHUB_TOKEN:
    secure: 4BISwFjqqswZYt/WHI0FamI/FD4oSsX/nYk/fD+qQeehSWPQugixI1DaMgXgatmi
  PHP_BUILD_CACHE_BASE_DIR: c:\build-cache
  PHP_BUILD_OBJ_DIR: c:\obj
  PHP_BUILD_CACHE_SDK_DIR: c:\build-cache\sdk
  PHP_BUILD_SDK_BRANCH: php-sdk-2.2.0
  SDK_REMOTE: https://github.com/OSTC/php-sdk-binary-tools.git
  SDK_BRANCH: php-sdk-2.2.0

  matrix:
    - PHP_REL: 8.0
      ARCHITECTURE: x64
      ZTS_STATE: enable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PHP_BUILD_CRT: vs16
    - PHP_REL: 8.0
      ARCHITECTURE: x64
      ZTS_STATE: disable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PHP_BUILD_CRT: vs16
    - PHP_REL: 8.0
      ARCHITECTURE: x86
      ZTS_STATE: enable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PHP_BUILD_CRT: vs16
    - PHP_REL: 8.0
      ARCHITECTURE: x86
      ZTS_STATE: disable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PHP_BUILD_CRT: vs16
    - PHP_REL: 7.4
      ARCHITECTURE: x64
      ZTS_STATE: enable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_BUILD_CRT: vc15
    - PHP_REL: 7.3
      ARCHITECTURE: x64
      ZTS_STATE: enable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_BUILD_CRT: vc15
    - PHP_REL: 7.2
      ARCHITECTURE: x64
      ZTS_STATE: enable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_BUILD_CRT: vc15
    - PHP_REL: 7.4
      ARCHITECTURE: x64
      ZTS_STATE: disable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_BUILD_CRT: vc15
    - PHP_REL: 7.3
      ARCHITECTURE: x64
      ZTS_STATE: disable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_BUILD_CRT: vc15
    - PHP_REL: 7.2
      ARCHITECTURE: x64
      ZTS_STATE: disable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_BUILD_CRT: vc15
    - PHP_REL: 7.4
      ARCHITECTURE: x86
      ZTS_STATE: enable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_BUILD_CRT: vc15
    - PHP_REL: 7.3
      ARCHITECTURE: x86
      ZTS_STATE: enable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_BUILD_CRT: vc15
    - PHP_REL: 7.2
      ARCHITECTURE: x86
      ZTS_STATE: enable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_BUILD_CRT: vc15
    - PHP_REL: 7.4
      ARCHITECTURE: x86
      ZTS_STATE: disable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_BUILD_CRT: vc15
    - PHP_REL: 7.3
      ARCHITECTURE: x86
      ZTS_STATE: disable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_BUILD_CRT: vc15
    - PHP_REL: 7.2
      ARCHITECTURE: x86
      ZTS_STATE: disable
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PHP_BUILD_CRT: vc15

install:
  - .appveyor\install.cmd

build_script:
  - .appveyor\build.cmd
deploy:
  release: php_tideways_xhprof-v$(APPVEYOR_BUILD_VERSION)
  description: '发布 php_tideways 扩展'
  provider: GitHub
  auth_token:
    secure: $env:GITHUB_TOKEN # your encrypted token from GitHub
  artifact: build\*.zip            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only